name: Update map.md

on:
  push:
    branches: ["master"]

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python 3.9
        uses: actions/setup-python@v3
        with:
          python-version: "3.9"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests
      - name: Run map.py
        run: |
          python map.py
      - name: Commit
        run: |
          git config --global user.email "me@example.com"
          git config --global user.name "Github Actions"
          git add map.md
          git commit -m "Actions: 更新map.md" -a
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: 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
